list_of_mqtt_topics = [ ("/devices/wb-mai6_89/controls/IN 1 N Value", 0),
                        ("/devices/wb-mai6_89/controls/IN 2 N Value", 0),
                        ("/devices/wb-mai6_89/controls/IN 3 N Value", 0),
                        ("/devices/wb-mai6_89/controls/IN 4 N Value", 0),
                        ]

ch1_topic_list = [("/devices/Channel_1/controls/ControlMode", 0),
                   ("/devices/Channel_1/controls/SWPeriod1State", 0),
                   ("/devices/Channel_1/controls/SWPeriod1Start", 0),
                   ("/devices/Channel_1/controls/SWPeriod1Stop", 0),
                   ("/devices/Channel_1/controls/SWPeriod2State", 0),
                   ("/devices/Channel_1/controls/SWPeriod2Start", 0),
                   ("/devices/Channel_1/controls/SWPeriod2Stop", 0),
                   ("/devices/Channel_1/controls/SWPeriod3State", 0),
                   ("/devices/Channel_1/controls/SWPeriod3Start", 0),
                   ("/devices/Channel_1/controls/SWPeriod3Stop", 0),
                   ("/devices/Channel_1/controls/SWPeriod4State", 0),
                   ("/devices/Channel_1/controls/SWPeriod4Start", 0),
                   ("/devices/Channel_1/controls/SWPeriod4Stop", 0),
                   ("/devices/Channel_1/controls/WeekStart", 0),
                   ("/devices/Channel_1/controls/WeekStop", 0),
                   ("/devices/Channel_1/controls/WeekendStart", 0),
                   ("/devices/Channel_1/controls/WeekendStop", 0),
                   ("/devices/Channel_1/controls/VentPipeDiameter", 0),
                   ("/devices/Channel_1/controls/VentPipeIOHeight", 0),
                   ("/devices/Channel_1/controls/VentPipeLength", 0),
                   ("/devices/Channel_1/controls/RoomArea", 0),
                   ("/devices/Channel_1/controls/AirExchangeValue", 0),
                   ]