
lorawan_sens_parser = [("application/9f1832a7-2862-4e8e-9c20-0f8342e689de/device/a840415711866a85/event/up", 0),
                       ]

alarm_service = [("/devices/GeneralInfo/controls/AlarmSignalType", 0),
                 ("/devices/GeneralInfo/controls/AlarmSignalValue", 0),
                 ("/devices/GeneralInfo/controls/PeriodicAlarmPerMin", 0),
                 ("/devices/GeneralInfo/controls/RepeatAlarmPerMin", 0),
                 ("/devices/GeneralInfo/controls/RepeatAlarmTimes", 0),
                 ("/devices/GeneralInfo/controls/AlarmSignalState", 0),
                 ("/devices/wb-w1/controls/28-3c01d075c9e9/meta/error", 0),
                 ("/devices/wb-mai6_89/controls/IN 1 N Voltage/meta/error", 0),
                 ("/devices/AlarmService/controls/OutdoorTempSensStatus", 0),
                 ("/devices/AlarmService/controls/VentChannelStatus1", 0),
                 ]

ch1_topic_list = [("/devices/Channel_1/controls/ControlMode", 0),
                   ("/devices/Channel_1/controls/SWPeriod1State", 0),
                   ("/devices/Channel_1/controls/SWPeriod1Start", 0),
                   ("/devices/Channel_1/controls/SWPeriod1Stop", 0),
                   ("/devices/Channel_1/controls/SWPeriod2State", 0),
                   ("/devices/Channel_1/controls/SWPeriod2Start", 0),
                   ("/devices/Channel_1/controls/SWPeriod2Stop", 0),
                   ("/devices/Channel_1/controls/SWPeriod3State", 0),
                   ("/devices/Channel_1/controls/SWPeriod3Start", 0),
                   ("/devices/Channel_1/controls/SWPeriod3Stop", 0),
                   ("/devices/Channel_1/controls/SWPeriod4State", 0),
                   ("/devices/Channel_1/controls/SWPeriod4Start", 0),
                   ("/devices/Channel_1/controls/SWPeriod4Stop", 0),
                   ("/devices/Channel_1/controls/WeekStart", 0),
                   ("/devices/Channel_1/controls/WeekStop", 0),
                   ("/devices/Channel_1/controls/WeekendStart", 0),
                   ("/devices/Channel_1/controls/WeekendStop", 0),
                   ("/devices/Channel_1/controls/VentPipeDiameter", 0),
                   ("/devices/Channel_1/controls/VentPipeIOHeight", 0),
                   ("/devices/Channel_1/controls/VentPipeLength", 0),
                   ("/devices/Channel_1/controls/RoomArea", 0),
                   ("/devices/Channel_1/controls/AirExchangeSet", 0),
                   ("/devices/wb-w1/controls/28-3c01d075c9e9", 0),
                   ("/devices/LorawanSensors/controls/Temperature1", 0),
                   ("/devices/GeneralInfo/controls/VacationState", 0),
                   ("/devices/GeneralInfo/controls/VacationValue1", 0),
                   ("/devices/GeneralInfo/controls/VacationValue2", 0),
                   ("/devices/Channel_1/controls/UpdatePeriod", 0),
                   ("/devices/Channel_1/controls/FeedbackAngle", 0),
                   ("/devices/AlarmService/controls/VentChannelStatus1", 0),

                   ("/devices/Channel_1/controls/EcoCoefState", 0),
                   ("/devices/Channel_1/controls/EcoCoefValue", 0),
                   ]

ch2_topic_list = [("/devices/Channel_2/controls/ControlMode", 0),
                   ("/devices/Channel_2/controls/SWPeriod1State", 0),
                   ("/devices/Channel_2/controls/SWPeriod1Start", 0),
                   ("/devices/Channel_2/controls/SWPeriod1Stop", 0),
                   ("/devices/Channel_2/controls/SWPeriod2State", 0),
                   ("/devices/Channel_2/controls/SWPeriod2Start", 0),
                   ("/devices/Channel_2/controls/SWPeriod2Stop", 0),
                   ("/devices/Channel_2/controls/SWPeriod3State", 0),
                   ("/devices/Channel_2/controls/SWPeriod3Start", 0),
                   ("/devices/Channel_2/controls/SWPeriod3Stop", 0),
                   ("/devices/Channel_2/controls/SWPeriod4State", 0),
                   ("/devices/Channel_2/controls/SWPeriod4Start", 0),
                   ("/devices/Channel_2/controls/SWPeriod4Stop", 0),
                   ("/devices/Channel_2/controls/WeekStart", 0),
                   ("/devices/Channel_2/controls/WeekStop", 0),
                   ("/devices/Channel_2/controls/WeekendStart", 0),
                   ("/devices/Channel_2/controls/WeekendStop", 0),
                   ("/devices/Channel_2/controls/VentPipeDiameter", 0),
                   ("/devices/Channel_2/controls/VentPipeIOHeight", 0),
                   ("/devices/Channel_2/controls/VentPipeLength", 0),
                   ("/devices/Channel_2/controls/RoomArea", 0),
                   ("/devices/Channel_2/controls/AirExchangeSet", 0),
                   ("/devices/wb-w1/controls/28-3c01d075c9e9", 0),
                   ("/devices/LorawanSensors/controls/Temperature1", 0),
                   ("/devices/GeneralInfo/controls/VacationState", 0),
                   ("/devices/GeneralInfo/controls/VacationValue1", 0),
                   ("/devices/GeneralInfo/controls/VacationValue2", 0),
                   ("/devices/Channel_2/controls/UpdatePeriod", 0),
                   ("/devices/Channel_2/controls/FeedbackAngle", 0),
                   ("/devices/AlarmService/controls/VentChannelStatus2", 0),
                   ]

ch3_topic_list = [("/devices/Channel_3/controls/ControlMode", 0),
                   ("/devices/Channel_3/controls/SWPeriod1State", 0),
                   ("/devices/Channel_3/controls/SWPeriod1Start", 0),
                   ("/devices/Channel_3/controls/SWPeriod1Stop", 0),
                   ("/devices/Channel_3/controls/SWPeriod2State", 0),
                   ("/devices/Channel_3/controls/SWPeriod2Start", 0),
                   ("/devices/Channel_3/controls/SWPeriod2Stop", 0),
                   ("/devices/Channel_3/controls/SWPeriod3State", 0),
                   ("/devices/Channel_3/controls/SWPeriod3Start", 0),
                   ("/devices/Channel_3/controls/SWPeriod3Stop", 0),
                   ("/devices/Channel_3/controls/SWPeriod4State", 0),
                   ("/devices/Channel_3/controls/SWPeriod4Start", 0),
                   ("/devices/Channel_3/controls/SWPeriod4Stop", 0),
                   ("/devices/Channel_3/controls/WeekStart", 0),
                   ("/devices/Channel_3/controls/WeekStop", 0),
                   ("/devices/Channel_3/controls/WeekendStart", 0),
                   ("/devices/Channel_3/controls/WeekendStop", 0),
                   ("/devices/Channel_3/controls/VentPipeDiameter", 0),
                   ("/devices/Channel_3/controls/VentPipeIOHeight", 0),
                   ("/devices/Channel_3/controls/VentPipeLength", 0),
                   ("/devices/Channel_3/controls/RoomArea", 0),
                   ("/devices/Channel_3/controls/AirExchangeSet", 0),
                   ("/devices/wb-w1/controls/28-3c01d075c9e9", 0),
                   ("/devices/LorawanSensors/controls/Temperature1", 0),
                   ("/devices/GeneralInfo/controls/VacationState", 0),
                   ("/devices/GeneralInfo/controls/VacationValue1", 0),
                   ("/devices/GeneralInfo/controls/VacationValue2", 0),
                   ("/devices/Channel_3/controls/UpdatePeriod", 0),
                   ("/devices/Channel_3/controls/FeedbackAngle", 0),
                   ("/devices/AlarmService/controls/VentChannelStatus3", 0),
                   ]

ch4_topic_list = [("/devices/Channel_4/controls/ControlMode", 0),
                   ("/devices/Channel_4/controls/SWPeriod1State", 0),
                   ("/devices/Channel_4/controls/SWPeriod1Start", 0),
                   ("/devices/Channel_4/controls/SWPeriod1Stop", 0),
                   ("/devices/Channel_4/controls/SWPeriod2State", 0),
                   ("/devices/Channel_4/controls/SWPeriod2Start", 0),
                   ("/devices/Channel_4/controls/SWPeriod2Stop", 0),
                   ("/devices/Channel_4/controls/SWPeriod3State", 0),
                   ("/devices/Channel_4/controls/SWPeriod3Start", 0),
                   ("/devices/Channel_4/controls/SWPeriod3Stop", 0),
                   ("/devices/Channel_4/controls/SWPeriod4State", 0),
                   ("/devices/Channel_4/controls/SWPeriod4Start", 0),
                   ("/devices/Channel_4/controls/SWPeriod4Stop", 0),
                   ("/devices/Channel_4/controls/WeekStart", 0),
                   ("/devices/Channel_4/controls/WeekStop", 0),
                   ("/devices/Channel_4/controls/WeekendStart", 0),
                   ("/devices/Channel_4/controls/WeekendStop", 0),
                   ("/devices/Channel_4/controls/VentPipeDiameter", 0),
                   ("/devices/Channel_4/controls/VentPipeIOHeight", 0),
                   ("/devices/Channel_4/controls/VentPipeLength", 0),
                   ("/devices/Channel_4/controls/RoomArea", 0),
                   ("/devices/Channel_4/controls/AirExchangeSet", 0),
                   ("/devices/wb-w1/controls/28-3c01d075c9e9", 0),
                   ("/devices/LorawanSensors/controls/Temperature1", 0),
                   ("/devices/GeneralInfo/controls/VacationState", 0),
                   ("/devices/GeneralInfo/controls/VacationValue1", 0),
                   ("/devices/GeneralInfo/controls/VacationValue2", 0),
                   ("/devices/Channel_4/controls/UpdatePeriod", 0),
                   ("/devices/Channel_4/controls/FeedbackAngle", 0),
                   ("/devices/AlarmService/controls/VentChannelStatus4", 0),
                   ]